// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stt.proto

package SpeechToText;

public final class Stt {
  private Stt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpeechChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpeechToText.SpeechChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>string lang = 3;</code>
     */
    java.lang.String getLang();
    /**
     * <code>string lang = 3;</code>
     */
    com.google.protobuf.ByteString
        getLangBytes();

    /**
     * <code>string demo = 4;</code>
     */
    java.lang.String getDemo();
    /**
     * <code>string demo = 4;</code>
     */
    com.google.protobuf.ByteString
        getDemoBytes();
  }
  /**
   * <pre>
   * audio chunk
   * </pre>
   *
   * Protobuf type {@code SpeechToText.SpeechChunk}
   */
  public  static final class SpeechChunk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpeechToText.SpeechChunk)
      SpeechChunkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpeechChunk.newBuilder() to construct.
    private SpeechChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeechChunk() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      token_ = "";
      lang_ = "";
      demo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SpeechChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              content_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lang_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              demo_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpeechToText.Stt.internal_static_SpeechToText_SpeechChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpeechToText.Stt.internal_static_SpeechToText_SpeechChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpeechToText.Stt.SpeechChunk.class, SpeechToText.Stt.SpeechChunk.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANG_FIELD_NUMBER = 3;
    private volatile java.lang.Object lang_;
    /**
     * <code>string lang = 3;</code>
     */
    public java.lang.String getLang() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lang_ = s;
        return s;
      }
    }
    /**
     * <code>string lang = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLangBytes() {
      java.lang.Object ref = lang_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lang_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEMO_FIELD_NUMBER = 4;
    private volatile java.lang.Object demo_;
    /**
     * <code>string demo = 4;</code>
     */
    public java.lang.String getDemo() {
      java.lang.Object ref = demo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        demo_ = s;
        return s;
      }
    }
    /**
     * <code>string demo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDemoBytes() {
      java.lang.Object ref = demo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        demo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeBytes(1, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      if (!getLangBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lang_);
      }
      if (!getDemoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, demo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      if (!getLangBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lang_);
      }
      if (!getDemoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, demo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SpeechToText.Stt.SpeechChunk)) {
        return super.equals(obj);
      }
      SpeechToText.Stt.SpeechChunk other = (SpeechToText.Stt.SpeechChunk) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getLang()
          .equals(other.getLang());
      result = result && getDemo()
          .equals(other.getDemo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + LANG_FIELD_NUMBER;
      hash = (53 * hash) + getLang().hashCode();
      hash = (37 * hash) + DEMO_FIELD_NUMBER;
      hash = (53 * hash) + getDemo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SpeechToText.Stt.SpeechChunk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpeechToText.Stt.SpeechChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.SpeechChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.SpeechChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SpeechToText.Stt.SpeechChunk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * audio chunk
     * </pre>
     *
     * Protobuf type {@code SpeechToText.SpeechChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpeechToText.SpeechChunk)
        SpeechToText.Stt.SpeechChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SpeechToText.Stt.internal_static_SpeechToText_SpeechChunk_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SpeechToText.Stt.internal_static_SpeechToText_SpeechChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SpeechToText.Stt.SpeechChunk.class, SpeechToText.Stt.SpeechChunk.Builder.class);
      }

      // Construct using SpeechToText.Stt.SpeechChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;

        token_ = "";

        lang_ = "";

        demo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SpeechToText.Stt.internal_static_SpeechToText_SpeechChunk_descriptor;
      }

      @java.lang.Override
      public SpeechToText.Stt.SpeechChunk getDefaultInstanceForType() {
        return SpeechToText.Stt.SpeechChunk.getDefaultInstance();
      }

      @java.lang.Override
      public SpeechToText.Stt.SpeechChunk build() {
        SpeechToText.Stt.SpeechChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SpeechToText.Stt.SpeechChunk buildPartial() {
        SpeechToText.Stt.SpeechChunk result = new SpeechToText.Stt.SpeechChunk(this);
        result.content_ = content_;
        result.token_ = token_;
        result.lang_ = lang_;
        result.demo_ = demo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SpeechToText.Stt.SpeechChunk) {
          return mergeFrom((SpeechToText.Stt.SpeechChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SpeechToText.Stt.SpeechChunk other) {
        if (other == SpeechToText.Stt.SpeechChunk.getDefaultInstance()) return this;
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getLang().isEmpty()) {
          lang_ = other.lang_;
          onChanged();
        }
        if (!other.getDemo().isEmpty()) {
          demo_ = other.demo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SpeechToText.Stt.SpeechChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SpeechToText.Stt.SpeechChunk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lang_ = "";
      /**
       * <code>string lang = 3;</code>
       */
      public java.lang.String getLang() {
        java.lang.Object ref = lang_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lang_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lang = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLangBytes() {
        java.lang.Object ref = lang_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lang_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lang = 3;</code>
       */
      public Builder setLang(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lang_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lang = 3;</code>
       */
      public Builder clearLang() {
        
        lang_ = getDefaultInstance().getLang();
        onChanged();
        return this;
      }
      /**
       * <code>string lang = 3;</code>
       */
      public Builder setLangBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lang_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object demo_ = "";
      /**
       * <code>string demo = 4;</code>
       */
      public java.lang.String getDemo() {
        java.lang.Object ref = demo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          demo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string demo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDemoBytes() {
        java.lang.Object ref = demo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          demo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string demo = 4;</code>
       */
      public Builder setDemo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        demo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string demo = 4;</code>
       */
      public Builder clearDemo() {
        
        demo_ = getDefaultInstance().getDemo();
        onChanged();
        return this;
      }
      /**
       * <code>string demo = 4;</code>
       */
      public Builder setDemoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        demo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpeechToText.SpeechChunk)
    }

    // @@protoc_insertion_point(class_scope:SpeechToText.SpeechChunk)
    private static final SpeechToText.Stt.SpeechChunk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SpeechToText.Stt.SpeechChunk();
    }

    public static SpeechToText.Stt.SpeechChunk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeechChunk>
        PARSER = new com.google.protobuf.AbstractParser<SpeechChunk>() {
      @java.lang.Override
      public SpeechChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpeechChunk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpeechChunk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeechChunk> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SpeechToText.Stt.SpeechChunk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TranscriptChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpeechToText.TranscriptChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string asr = 1;</code>
     */
    java.lang.String getAsr();
    /**
     * <code>string asr = 1;</code>
     */
    com.google.protobuf.ByteString
        getAsrBytes();

    /**
     * <code>string transcript = 2;</code>
     */
    java.lang.String getTranscript();
    /**
     * <code>string transcript = 2;</code>
     */
    com.google.protobuf.ByteString
        getTranscriptBytes();

    /**
     * <code>bool is_final = 3;</code>
     */
    boolean getIsFinal();

    /**
     * <code>float confidence = 4;</code>
     */
    float getConfidence();

    /**
     * <code>string answer = 5;</code>
     */
    java.lang.String getAnswer();
    /**
     * <code>string answer = 5;</code>
     */
    com.google.protobuf.ByteString
        getAnswerBytes();

    /**
     * <code>string image_url = 6;</code>
     */
    java.lang.String getImageUrl();
    /**
     * <code>string image_url = 6;</code>
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();

    /**
     * <code>string image_yes_no = 7;</code>
     */
    java.lang.String getImageYesNo();
    /**
     * <code>string image_yes_no = 7;</code>
     */
    com.google.protobuf.ByteString
        getImageYesNoBytes();
  }
  /**
   * <pre>
   * response
   * </pre>
   *
   * Protobuf type {@code SpeechToText.TranscriptChunk}
   */
  public  static final class TranscriptChunk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpeechToText.TranscriptChunk)
      TranscriptChunkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TranscriptChunk.newBuilder() to construct.
    private TranscriptChunk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TranscriptChunk() {
      asr_ = "";
      transcript_ = "";
      isFinal_ = false;
      confidence_ = 0F;
      answer_ = "";
      imageUrl_ = "";
      imageYesNo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TranscriptChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              asr_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              transcript_ = s;
              break;
            }
            case 24: {

              isFinal_ = input.readBool();
              break;
            }
            case 37: {

              confidence_ = input.readFloat();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              answer_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              imageUrl_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              imageYesNo_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpeechToText.Stt.internal_static_SpeechToText_TranscriptChunk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpeechToText.Stt.internal_static_SpeechToText_TranscriptChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpeechToText.Stt.TranscriptChunk.class, SpeechToText.Stt.TranscriptChunk.Builder.class);
    }

    public static final int ASR_FIELD_NUMBER = 1;
    private volatile java.lang.Object asr_;
    /**
     * <code>string asr = 1;</code>
     */
    public java.lang.String getAsr() {
      java.lang.Object ref = asr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asr_ = s;
        return s;
      }
    }
    /**
     * <code>string asr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAsrBytes() {
      java.lang.Object ref = asr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSCRIPT_FIELD_NUMBER = 2;
    private volatile java.lang.Object transcript_;
    /**
     * <code>string transcript = 2;</code>
     */
    public java.lang.String getTranscript() {
      java.lang.Object ref = transcript_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transcript_ = s;
        return s;
      }
    }
    /**
     * <code>string transcript = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTranscriptBytes() {
      java.lang.Object ref = transcript_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transcript_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_FINAL_FIELD_NUMBER = 3;
    private boolean isFinal_;
    /**
     * <code>bool is_final = 3;</code>
     */
    public boolean getIsFinal() {
      return isFinal_;
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 4;
    private float confidence_;
    /**
     * <code>float confidence = 4;</code>
     */
    public float getConfidence() {
      return confidence_;
    }

    public static final int ANSWER_FIELD_NUMBER = 5;
    private volatile java.lang.Object answer_;
    /**
     * <code>string answer = 5;</code>
     */
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        answer_ = s;
        return s;
      }
    }
    /**
     * <code>string answer = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_URL_FIELD_NUMBER = 6;
    private volatile java.lang.Object imageUrl_;
    /**
     * <code>string image_url = 6;</code>
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string image_url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_YES_NO_FIELD_NUMBER = 7;
    private volatile java.lang.Object imageYesNo_;
    /**
     * <code>string image_yes_no = 7;</code>
     */
    public java.lang.String getImageYesNo() {
      java.lang.Object ref = imageYesNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageYesNo_ = s;
        return s;
      }
    }
    /**
     * <code>string image_yes_no = 7;</code>
     */
    public com.google.protobuf.ByteString
        getImageYesNoBytes() {
      java.lang.Object ref = imageYesNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageYesNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAsrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, asr_);
      }
      if (!getTranscriptBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transcript_);
      }
      if (isFinal_ != false) {
        output.writeBool(3, isFinal_);
      }
      if (confidence_ != 0F) {
        output.writeFloat(4, confidence_);
      }
      if (!getAnswerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, answer_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, imageUrl_);
      }
      if (!getImageYesNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, imageYesNo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAsrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, asr_);
      }
      if (!getTranscriptBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transcript_);
      }
      if (isFinal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFinal_);
      }
      if (confidence_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, confidence_);
      }
      if (!getAnswerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, answer_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, imageUrl_);
      }
      if (!getImageYesNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, imageYesNo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SpeechToText.Stt.TranscriptChunk)) {
        return super.equals(obj);
      }
      SpeechToText.Stt.TranscriptChunk other = (SpeechToText.Stt.TranscriptChunk) obj;

      boolean result = true;
      result = result && getAsr()
          .equals(other.getAsr());
      result = result && getTranscript()
          .equals(other.getTranscript());
      result = result && (getIsFinal()
          == other.getIsFinal());
      result = result && (
          java.lang.Float.floatToIntBits(getConfidence())
          == java.lang.Float.floatToIntBits(
              other.getConfidence()));
      result = result && getAnswer()
          .equals(other.getAnswer());
      result = result && getImageUrl()
          .equals(other.getImageUrl());
      result = result && getImageYesNo()
          .equals(other.getImageYesNo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ASR_FIELD_NUMBER;
      hash = (53 * hash) + getAsr().hashCode();
      hash = (37 * hash) + TRANSCRIPT_FIELD_NUMBER;
      hash = (53 * hash) + getTranscript().hashCode();
      hash = (37 * hash) + IS_FINAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinal());
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidence());
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswer().hashCode();
      hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (37 * hash) + IMAGE_YES_NO_FIELD_NUMBER;
      hash = (53 * hash) + getImageYesNo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpeechToText.Stt.TranscriptChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.TranscriptChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpeechToText.Stt.TranscriptChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SpeechToText.Stt.TranscriptChunk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * response
     * </pre>
     *
     * Protobuf type {@code SpeechToText.TranscriptChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpeechToText.TranscriptChunk)
        SpeechToText.Stt.TranscriptChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SpeechToText.Stt.internal_static_SpeechToText_TranscriptChunk_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SpeechToText.Stt.internal_static_SpeechToText_TranscriptChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SpeechToText.Stt.TranscriptChunk.class, SpeechToText.Stt.TranscriptChunk.Builder.class);
      }

      // Construct using SpeechToText.Stt.TranscriptChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        asr_ = "";

        transcript_ = "";

        isFinal_ = false;

        confidence_ = 0F;

        answer_ = "";

        imageUrl_ = "";

        imageYesNo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SpeechToText.Stt.internal_static_SpeechToText_TranscriptChunk_descriptor;
      }

      @java.lang.Override
      public SpeechToText.Stt.TranscriptChunk getDefaultInstanceForType() {
        return SpeechToText.Stt.TranscriptChunk.getDefaultInstance();
      }

      @java.lang.Override
      public SpeechToText.Stt.TranscriptChunk build() {
        SpeechToText.Stt.TranscriptChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SpeechToText.Stt.TranscriptChunk buildPartial() {
        SpeechToText.Stt.TranscriptChunk result = new SpeechToText.Stt.TranscriptChunk(this);
        result.asr_ = asr_;
        result.transcript_ = transcript_;
        result.isFinal_ = isFinal_;
        result.confidence_ = confidence_;
        result.answer_ = answer_;
        result.imageUrl_ = imageUrl_;
        result.imageYesNo_ = imageYesNo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SpeechToText.Stt.TranscriptChunk) {
          return mergeFrom((SpeechToText.Stt.TranscriptChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SpeechToText.Stt.TranscriptChunk other) {
        if (other == SpeechToText.Stt.TranscriptChunk.getDefaultInstance()) return this;
        if (!other.getAsr().isEmpty()) {
          asr_ = other.asr_;
          onChanged();
        }
        if (!other.getTranscript().isEmpty()) {
          transcript_ = other.transcript_;
          onChanged();
        }
        if (other.getIsFinal() != false) {
          setIsFinal(other.getIsFinal());
        }
        if (other.getConfidence() != 0F) {
          setConfidence(other.getConfidence());
        }
        if (!other.getAnswer().isEmpty()) {
          answer_ = other.answer_;
          onChanged();
        }
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        if (!other.getImageYesNo().isEmpty()) {
          imageYesNo_ = other.imageYesNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SpeechToText.Stt.TranscriptChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SpeechToText.Stt.TranscriptChunk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object asr_ = "";
      /**
       * <code>string asr = 1;</code>
       */
      public java.lang.String getAsr() {
        java.lang.Object ref = asr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAsrBytes() {
        java.lang.Object ref = asr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asr = 1;</code>
       */
      public Builder setAsr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string asr = 1;</code>
       */
      public Builder clearAsr() {
        
        asr_ = getDefaultInstance().getAsr();
        onChanged();
        return this;
      }
      /**
       * <code>string asr = 1;</code>
       */
      public Builder setAsrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        asr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transcript_ = "";
      /**
       * <code>string transcript = 2;</code>
       */
      public java.lang.String getTranscript() {
        java.lang.Object ref = transcript_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transcript_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transcript = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTranscriptBytes() {
        java.lang.Object ref = transcript_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transcript_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transcript = 2;</code>
       */
      public Builder setTranscript(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transcript_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transcript = 2;</code>
       */
      public Builder clearTranscript() {
        
        transcript_ = getDefaultInstance().getTranscript();
        onChanged();
        return this;
      }
      /**
       * <code>string transcript = 2;</code>
       */
      public Builder setTranscriptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transcript_ = value;
        onChanged();
        return this;
      }

      private boolean isFinal_ ;
      /**
       * <code>bool is_final = 3;</code>
       */
      public boolean getIsFinal() {
        return isFinal_;
      }
      /**
       * <code>bool is_final = 3;</code>
       */
      public Builder setIsFinal(boolean value) {
        
        isFinal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_final = 3;</code>
       */
      public Builder clearIsFinal() {
        
        isFinal_ = false;
        onChanged();
        return this;
      }

      private float confidence_ ;
      /**
       * <code>float confidence = 4;</code>
       */
      public float getConfidence() {
        return confidence_;
      }
      /**
       * <code>float confidence = 4;</code>
       */
      public Builder setConfidence(float value) {
        
        confidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float confidence = 4;</code>
       */
      public Builder clearConfidence() {
        
        confidence_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object answer_ = "";
      /**
       * <code>string answer = 5;</code>
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          answer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string answer = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string answer = 5;</code>
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 5;</code>
       */
      public Builder clearAnswer() {
        
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 5;</code>
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        answer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageUrl_ = "";
      /**
       * <code>string image_url = 6;</code>
       */
      public java.lang.String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image_url = 6;</code>
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        java.lang.Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_url = 6;</code>
       */
      public Builder setImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 6;</code>
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 6;</code>
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageYesNo_ = "";
      /**
       * <code>string image_yes_no = 7;</code>
       */
      public java.lang.String getImageYesNo() {
        java.lang.Object ref = imageYesNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageYesNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string image_yes_no = 7;</code>
       */
      public com.google.protobuf.ByteString
          getImageYesNoBytes() {
        java.lang.Object ref = imageYesNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageYesNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_yes_no = 7;</code>
       */
      public Builder setImageYesNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageYesNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_yes_no = 7;</code>
       */
      public Builder clearImageYesNo() {
        
        imageYesNo_ = getDefaultInstance().getImageYesNo();
        onChanged();
        return this;
      }
      /**
       * <code>string image_yes_no = 7;</code>
       */
      public Builder setImageYesNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageYesNo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SpeechToText.TranscriptChunk)
    }

    // @@protoc_insertion_point(class_scope:SpeechToText.TranscriptChunk)
    private static final SpeechToText.Stt.TranscriptChunk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SpeechToText.Stt.TranscriptChunk();
    }

    public static SpeechToText.Stt.TranscriptChunk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TranscriptChunk>
        PARSER = new com.google.protobuf.AbstractParser<TranscriptChunk>() {
      @java.lang.Override
      public TranscriptChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TranscriptChunk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TranscriptChunk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TranscriptChunk> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SpeechToText.Stt.TranscriptChunk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechToText_SpeechChunk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechToText_SpeechChunk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechToText_TranscriptChunk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechToText_TranscriptChunk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tstt.proto\022\014SpeechToText\"I\n\013SpeechChunk" +
      "\022\017\n\007content\030\001 \001(\014\022\r\n\005token\030\002 \001(\t\022\014\n\004lang" +
      "\030\003 \001(\t\022\014\n\004demo\030\004 \001(\t\"\221\001\n\017TranscriptChunk" +
      "\022\013\n\003asr\030\001 \001(\t\022\022\n\ntranscript\030\002 \001(\t\022\020\n\010is_" +
      "final\030\003 \001(\010\022\022\n\nconfidence\030\004 \001(\002\022\016\n\006answe" +
      "r\030\005 \001(\t\022\021\n\timage_url\030\006 \001(\t\022\024\n\014image_yes_" +
      "no\030\007 \001(\t2\\\n\010Listener\022P\n\016DoSpeechToText\022\031" +
      ".SpeechToText.SpeechChunk\032\035.SpeechToText" +
      ".TranscriptChunk\"\000(\0010\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SpeechToText_SpeechChunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SpeechToText_SpeechChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechToText_SpeechChunk_descriptor,
        new java.lang.String[] { "Content", "Token", "Lang", "Demo", });
    internal_static_SpeechToText_TranscriptChunk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SpeechToText_TranscriptChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechToText_TranscriptChunk_descriptor,
        new java.lang.String[] { "Asr", "Transcript", "IsFinal", "Confidence", "Answer", "ImageUrl", "ImageYesNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
