# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x0cSpeechToText\"I\n\x0bSpeechChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04lang\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65mo\x18\x04 \x01(\t\"\x91\x01\n\x0fTranscriptChunk\x12\x0b\n\x03\x61sr\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x0e\n\x06\x61nswer\x18\x05 \x01(\t\x12\x11\n\timage_url\x18\x06 \x01(\t\x12\x14\n\x0cimage_yes_no\x18\x07 \x01(\t2\\\n\x08Listener\x12P\n\x0e\x44oSpeechToText\x12\x19.SpeechToText.SpeechChunk\x1a\x1d.SpeechToText.TranscriptChunk\"\x00(\x01\x30\x01\x62\x06proto3')



_SPEECHCHUNK = DESCRIPTOR.message_types_by_name['SpeechChunk']
_TRANSCRIPTCHUNK = DESCRIPTOR.message_types_by_name['TranscriptChunk']
SpeechChunk = _reflection.GeneratedProtocolMessageType('SpeechChunk', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHCHUNK,
  '__module__' : 'stt_pb2'
  # @@protoc_insertion_point(class_scope:SpeechToText.SpeechChunk)
  })
_sym_db.RegisterMessage(SpeechChunk)

TranscriptChunk = _reflection.GeneratedProtocolMessageType('TranscriptChunk', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIPTCHUNK,
  '__module__' : 'stt_pb2'
  # @@protoc_insertion_point(class_scope:SpeechToText.TranscriptChunk)
  })
_sym_db.RegisterMessage(TranscriptChunk)

_LISTENER = DESCRIPTOR.services_by_name['Listener']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPEECHCHUNK._serialized_start=27
  _SPEECHCHUNK._serialized_end=100
  _TRANSCRIPTCHUNK._serialized_start=103
  _TRANSCRIPTCHUNK._serialized_end=248
  _LISTENER._serialized_start=250
  _LISTENER._serialized_end=342
# @@protoc_insertion_point(module_scope)
